# Generated by Django 4.2.4 on 2023-11-05 18:08

import datetime
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('next_steps', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('use_case', models.CharField(max_length=256)),
                ('how_to_use', models.CharField(max_length=256)),
                ('side_effects', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=120)])),
                ('gender', models.CharField(max_length=64)),
                ('height', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=300)])),
                ('weight', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=200)])),
                ('name', models.CharField(max_length=128)),
                ('profession', models.CharField(default='Paediatrician', max_length=128)),
                ('preconditions', models.TextField()),
                ('allergies', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.TextField(default='')),
                ('name', models.CharField(default='', max_length=256)),
                ('duration', models.IntegerField(default=7, validators=[django.core.validators.MaxValueValidator(limit_value=100)])),
                ('dosage', models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=1000)])),
                ('finish_date', models.DateTimeField(default=datetime.datetime(2023, 11, 12, 18, 8, 58, 296122, tzinfo=datetime.timezone.utc))),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
